service: lift-demo-storage
configValidationMode: error

provider:
    name: aws
    region: us-east-1
    lambdaHashingVersion: 20201221

providers:
    aws:

functions:
    test:
        handler: function.handler
        runtime: nodejs14.x
        environment:
            BUCKET_NAME: ${construct:avatars.bucketName}

constructs:
    avatars:
        provider: aws
        type: storage

plugins:
    - ../../dist/src/plugin.js
