service: lift-demo-queues
configValidationMode: error

provider:
    name: aws
    region: us-east-1
    lambdaHashingVersion: 20201221
    environment:
        QUEUE_URL: ${construct:import.queueUrl}
    iam:
        role:
            statements:
                # Allow to send messages to SQS
                -   Effect: Allow
                    Action: sqs:SendMessage
                    Resource: ${construct:import.queueArn}

providers:
    aws:

functions:
    publisher:
        handler: publisher.handler
        runtime: nodejs14.x
        events:
            -   httpApi: 'GET /'

constructs:

    api:
        provider: aws
        type: http-api
        routes:
            '*':
                type: function
                handler: publisher.handler
                runtime: nodejs14.x
                environment:
                    # TODO: make the reference work
                    QUEUE_URL: https://sqs.us-east-1.amazonaws.com/416566615250/lift-demo-queues-dev-constructs-import
#                    QUEUE_URL: ${reference:import.queueUrl}

    import:
        provider: aws
        type: queue
        worker:
            type: function
            handler: worker.handler
        alarm: matthieu@mnapoli.fr

plugins:
    - ../../dist/src/plugin.js
