service: lift-demo-queues
configValidationMode: error

# Can we get rid of this?
provider:
    name: aws

providers:
    aws:

constructs:

    api:
        provider: aws
        type: http-api
        routes:
            '*':
                type: function
                handler: publisher.handler
                runtime: nodejs14.x
                environment:
                    # TODO: make the reference work
#                    QUEUE_URL: ${reference:import.queueUrl}
                    QUEUE_URL: https://sqs.us-east-1.amazonaws.com/416566615250/lift-demo-queues-dev-constructs-import

    import:
        provider: aws
        type: queue
        worker:
            type: function
            handler: worker.handler
        alarm: matthieu@mnapoli.fr

plugins:
    - ../../dist/src/plugin.js
